import { Button, Stack } from '@chakra-ui/react';
import { SignedIn, SignedOut } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Logo from '~/assets/Logo';
import AnimataedLayout from '~/components/AnimataedLayout';
import Main from '~/ui/Main/Main';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Spirit Home Front</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SignedIn>
				<Main
					user={<Main.User afterSignOutUrl="/signin" />}
					categorys={<Main.Categorys />}
				/>
			</SignedIn>
			<SignedOut>
				<AnimataedLayout
					container={{
						h: '100vh',
					}}
					delay={0}
				>
					<Stack alignItems="center" justifyContent="center">
						<Logo
							iconProps={{
								boxSize: 32,
								fill: 'blackAlpha.700',
							}}
						/>
						<Button
							as={Link}
							href="/signin"
							colorScheme="telegram"
							w="2xs"
						>
							Войти
						</Button>
					</Stack>
				</AnimataedLayout>
			</SignedOut>
		</>
	);
};

export default Home;
