import { Button } from '@chakra-ui/react';
import { SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import AnimataedLayout from '~/components/AnimataedLayout';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Spirit Home Front</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SignedIn>
				<UserButton afterSignOutUrl="/signin" />
			</SignedIn>
			<SignedOut>
				<AnimataedLayout
					container={{
						w: '100vw',
						h: '100vh',
					}}
				>
					<Button
						as={Link}
						href="/signin"
						colorScheme="telegram"
						w="2xs"
					>
						Войти
					</Button>
				</AnimataedLayout>
			</SignedOut>
		</>
	);
};

export default Home;
