import { Button } from '@chakra-ui/react';
import { SignedIn, SignedOut } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import AnimataedLayout from '~/components/AnimataedLayout';
import Main from '~/ui/Main/Main';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Spirit Home Front</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SignedIn>
				<Main
					user={<Main.User afterSignOutUrl="/signin" />}
					categorys={<Main.Categorys />}
				/>
			</SignedIn>
			<SignedOut>
				<AnimataedLayout
					container={{
						w: '10vw',
						h: '100vh',
					}}
					delay={0}
				>
					<Button
						as={Link}
						href="/signin"
						colorScheme="telegram"
						w="2xs"
					>
						Войти
					</Button>
				</AnimataedLayout>
			</SignedOut>
		</>
	);
};

export default Home;
